spring:
  config:
    import:
      - application-oauth.yml
      - optional:application-db.yml
  profiles:
    active:
      - dev
      - oauth
    include: oauth
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:tcp://localhost/~/secondboard
    username: sa
    password:
    driver-class-name: org.h2.Driver

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
    check-template-location: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace