spring:
#  config:
#    import:
#      - application-oauth.yml
#      - optional:application-db.yml
  profiles:
    active:
      - dev
      - oauth
    include: oauth

# spring.profiles.include : 애플리케이션에서 활성화되는 프로파일을 지정합니다
# spring.config.import : YAML 파일의 외부 구성을 가져올 때 사용됩니다
---
spring:
#  config:
#    activate:
#      on-profile: dev
  # on-profile : 특정 프로파일이 활성화되었을 때 사용할 추가 프로퍼티 파일을 지정하는 데 사용
  # 예시
  # on-profile: dev
  # additional-config: classpath:application-dev-datasource.yml
  # 이러면 dev가 활성화 됐을 때 dev-datasource 를 추가로 활성화한다
  datasource:
    url: jdbc:h2:tcp://localhost/~/secondboard
    username: sa
    password:
    driver-class-name: org.h2.Driver

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
    check-template-location: true

  data:
    web:
      pageable:
        default-page-size: 10
        page-parameter: page
        size-parameter: size

  # 라이브 리로드 관련 설정
  # 1. devtools 에서 livereload on 하면서, 파일 변경 감지되면 자동 재시작 되도록 restart enabled 해줌
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  # 2. LiveReload를 위해서 스프링이 정적파일 위치를 알 수 있도록 설정
  resources:
    static-location: file:src/main/resources/static/

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

